### ISSUE TITLE
Is it possible to make functions and types conform to the Swift naming convention?

### ISSUE THREAD

**Issue by Mx-Iris** [Wei18/github-rest-api-swift-openapi#22]

**Comment by Wei18** [comment]
It would be possible if we modify functions and types in the OAS.
For now, there are some discussions in the swift-openapi-generator,
please refer to the following issues for more ino.

- https://github.com/apple/swift-openapi-generator/issues/112

- https://github.com/apple/swift-openapi-generator/issues/107

**Comment by Mx-Iris** [comment]
> It would be possible if we modify functions and types in the OAS each time before swift code generated.如果我们在生成Swift代码之前每次修改OAS中的函数和类型，那么这是可能的。
> 
> For now, there are some discussions in the swift-openapi-generator,目前，swift-openapi-generator中有一些讨论 please refer to the following issues for more ino.请参考以下问题以获取更多信息。
> 
> * [Generator plugin for customizing the OpenAPI -> Swift name creation apple/swift-openapi-generator#112自定义OpenAPI生成器插件-> Swift名称创建apple/swift-openapi-generator#112](https://github.com/apple/swift-openapi-generator/issues/112)
> * [Generated models and types should follow Swift conventions apple/swift-openapi-generator#107生成的模型和类型应遵循Swift的约定 apple/swift-openapi-generator#107](https://github.com/apple/swift-openapi-generator/issues/107)

I see. Thanks for your answer

**Comment by wei18** [comment]
Hi @Mx-Iris,

Please try out [version 3.0.0](https://github.com/wei18/github-rest-api-swift-openapi/releases/tag/3.0.0).  
The feature was contributed by @ryansobol — big thanks to him!

**Comment by Mx-Iris** [comment]
@wei18 Thank you for the reminder. I'm glad to see that this is supported, and thank you to @ryansobol as well!

**Comment by ryansobol** [comment]
@Mx-Iris My pleasure!
